FROM python:3.12-slim

WORKDIR /app

COPY docker/pip.conf /etc/pip.conf

RUN pip install --no-cache-dir alembic sqlalchemy asyncpg psycopg2-binary

COPY packages/shared-models ./packages/shared-models
COPY migrations ./migrations

CMD ["alembic", "-c", "migrations/alembic.ini", "upgrade", "head"]
